"""empty message

Revision ID: 2f87fd3c662
Revises: None
Create Date: 2014-12-01 01:11:50.794755

"""

# revision identifiers, used by Alembic.
revision = '2f87fd3c662'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarios',
    sa.Column('_id', sa.Integer(), nullable=False),
    sa.Column('usuario', sa.String(length=12), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('senha', sa.String(length=32), nullable=True),
    sa.Column('data_de_cadastro', sa.DateTime(), nullable=True),
    sa.Column('role', sa.Integer(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('usuario')
    )
    op.create_table('cad_questoes',
    sa.Column('_id', sa.Integer(), nullable=False),
    sa.Column('enunciado', sa.String(length=255), nullable=True),
    sa.Column('alternativa_a', sa.String(), nullable=True),
    sa.Column('alternativa_b', sa.String(), nullable=True),
    sa.Column('alternativa_c', sa.String(), nullable=True),
    sa.Column('alternativa_d', sa.String(), nullable=True),
    sa.Column('alternativa_e', sa.String(), nullable=True),
    sa.Column('alternativa_correta', sa.String(length=1), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('data_de_envio', sa.DateTime(), nullable=True),
    sa.Column('enviada_por', sa.Integer(), nullable=False),
    sa.Column('revisada_por', sa.Integer(), nullable=True),
    sa.Column('observacoes', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['enviada_por'], ['usuarios._id'], ),
    sa.ForeignKeyConstraint(['revisada_por'], ['usuarios._id'], ),
    sa.PrimaryKeyConstraint('_id')
    )
    op.create_table('partidas',
    sa.Column('_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('data_da_partida', sa.DateTime(), nullable=True),
    sa.Column('questao_atual', sa.Integer(), nullable=False),
    sa.Column('acertos', sa.Integer(), nullable=True),
    sa.Column('cartas', sa.Integer(), nullable=True),
    sa.Column('pular', sa.Integer(), nullable=True),
    sa.Column('finalizada', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['questao_atual'], ['cad_questoes._id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios._id'], ),
    sa.PrimaryKeyConstraint('_id')
    )
    op.create_table('partidas_resposta',
    sa.Column('_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('questao_id', sa.Integer(), nullable=False),
    sa.Column('partida_id', sa.Integer(), nullable=False),
    sa.Column('alternativa_respondida', sa.String(length=1), nullable=True),
    sa.Column('resultado', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['partida_id'], ['partidas._id'], ),
    sa.ForeignKeyConstraint(['questao_id'], ['cad_questoes._id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios._id'], ),
    sa.PrimaryKeyConstraint('_id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('partidas_resposta')
    op.drop_table('partidas')
    op.drop_table('cad_questoes')
    op.drop_table('usuarios')
    ### end Alembic commands ###
